modLoader="javafml"
loaderVersion="[4,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="tamable_spiders"
version="3.0.1"
displayName="Tamable Spiders"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tameable-spiders"
logoFile="logo.png"
credits="Spiderman31807"
authors="Spiderman31807"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.tamable_spiders]]
modId="neoforge"
type="required"
versionRange="[21.1.190,)"
ordering="AFTER"
side="BOTH"

[[dependencies.tamable_spiders]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="AFTER"
side="BOTH"




# Start of user code block dependencies configuration
[[mixins]]
config="mixins.tamable_spiders.json"
# End of user code block dependencies configuration
